project_id = "sfcwoftgzxplbexcmzva"

[functions.paydunya-checkout]
verify_jwt = false

[functions.ai-forecast]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.ai-suggest]
verify_jwt = false

[functions.ai-detect-recurring]
verify_jwt = false