// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-accounts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-accounts.ts
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "List the signed-in user's payment accounts (cash, bank, mobile money, savings) with opening and real balances.",
  inputSchema: {
    include_archived: z.boolean().optional().describe("Include archived accounts. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("payment_accounts").select("id, name, type, icon, opening_balance, real_balance, status, archived_at, last_activity_at").is("deleted_at", null).order("created_at", { ascending: false });
    if (!include_archived) query = query.is("archived_at", null);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ accounts: data ?? [] });
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's recent transactions (income, expense, transfers). Supports date range, type and limit filters.",
  inputSchema: {
    type: z2.enum(["income", "expense"]).optional().describe("Filter by transaction type."),
    start_date: z2.string().optional().describe("ISO date (YYYY-MM-DD) lower bound, inclusive."),
    end_date: z2.string().optional().describe("ISO date (YYYY-MM-DD) upper bound, inclusive."),
    limit: z2.number().int().positive().max(200).optional().describe("Max rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, start_date, end_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("transactions").select("id, date, description, amount, type, notes, tags, category_id, account_id, is_transfer, created_at").is("deleted_at", null).order("date", { ascending: false }).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (type) query = query.eq("type", type);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ transactions: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_transaction_default = defineTool3({
  name: "create_transaction",
  title: "Create transaction",
  description: "Record a new income or expense transaction for the signed-in user. Amount must be positive; the type field determines direction. Use list_accounts / list_categories to look up ids.",
  inputSchema: {
    type: z3.enum(["income", "expense"]).describe("Direction of the transaction."),
    amount: z3.number().positive().describe("Amount in the account currency (positive number)."),
    description: z3.string().min(1).describe("Short human-readable label."),
    date: z3.string().optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    account_id: z3.string().uuid().optional().describe("Payment account id from list_accounts."),
    category_id: z3.string().uuid().optional().describe("Category id from list_categories."),
    notes: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("transactions").insert({
      user_id: ctx.getUserId(),
      type: input.type,
      amount: input.amount,
      description: input.description,
      date: input.date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      account_id: input.account_id ?? null,
      category_id: input.category_id ?? null,
      notes: input.notes ?? null
    }).select("id, date, description, amount, type, account_id, category_id").single();
    if (error) return errorResult(error.message);
    return jsonResult({ transaction: data });
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_categories_default = defineTool4({
  name: "list_categories",
  title: "List categories",
  description: "List the signed-in user's transaction categories (with icon, color and type).",
  inputSchema: {
    type: z4.enum(["income", "expense"]).optional().describe("Filter by category type.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("categories").select("id, name, icon, color, type, parent_category_id").order("name");
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ categories: data ?? [] });
  }
});

// src/lib/mcp/tools/list-budgets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_budgets_default = defineTool5({
  name: "list_budgets",
  title: "List budgets",
  description: "List the signed-in user's active budgets with amount, period, control type and category link.",
  inputSchema: {
    include_paused: z5.boolean().optional().describe("Include paused budgets. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_paused }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("budgets").select("id, name, amount, period, budget_type, control_type, category_id, alert_threshold, paused_at, occurrence_frequency, reference_date").is("deleted_at", null).is("archived_at", null).order("created_at", { ascending: false });
    if (!include_paused) query = query.is("paused_at", null);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ budgets: data ?? [] });
  }
});

// src/lib/mcp/tools/list-savings-goals.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_savings_goals_default = defineTool6({
  name: "list_savings_goals",
  title: "List savings goals",
  description: "List the signed-in user's savings goals with progress toward target amount.",
  inputSchema: {
    status: z6.enum(["active", "completed", "archived"]).optional().describe("Filter by goal status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("savings_goals").select("id, name, target_amount, current_amount, deadline, status, priority, monthly_contribution, icon, account_id").is("deleted_at", null).order("created_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ goals: data ?? [] });
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z7 } from "npm:zod@^3.25.76";
var financial_summary_default = defineTool7({
  name: "financial_summary",
  title: "Financial summary",
  description: "Compute total income, total expense and net balance for the signed-in user over a period. Transfers are excluded. Defaults to the current calendar month.",
  inputSchema: {
    start_date: z7.string().optional().describe("ISO date (YYYY-MM-DD). Defaults to first day of current month."),
    end_date: z7.string().optional().describe("ISO date (YYYY-MM-DD). Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const today = /* @__PURE__ */ new Date();
    const defaultStart = new Date(today.getFullYear(), today.getMonth(), 1).toISOString().slice(0, 10);
    const defaultEnd = today.toISOString().slice(0, 10);
    const from = start_date ?? defaultStart;
    const to = end_date ?? defaultEnd;
    const { data, error } = await supabase.from("transactions").select("amount, type, is_transfer").is("deleted_at", null).gte("date", from).lte("date", to);
    if (error) return errorResult(error.message);
    let income = 0;
    let expense = 0;
    for (const row of data ?? []) {
      if (row.is_transfer) continue;
      const amount = Number(row.amount) || 0;
      if (row.type === "income") income += amount;
      else if (row.type === "expense") expense += amount;
    }
    return jsonResult({
      period: { start_date: from, end_date: to },
      total_income: income,
      total_expense: expense,
      net: income - expense,
      transaction_count: data?.length ?? 0
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "sfcwoftgzxplbexcmzva";
var mcp_default = defineMcp({
  name: "budget-planner-pro-mcp",
  title: "Budget Planner Pro",
  version: "0.1.0",
  instructions: "Personal finance tools for Budget Planner Pro. Read the signed-in user's accounts, transactions, categories, budgets and savings goals, and record new income or expense entries. All amounts are in the user's app currency (default XOF / CFA franc). Transfers are excluded from income and expense summaries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_accounts_default,
    list_transactions_default,
    create_transaction_default,
    list_categories_default,
    list_budgets_default,
    list_savings_goals_default,
    financial_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
